---
- name: Download ETCD package
  get_url: 
    url: https://github.com/coreos/etcd/releases/download/v{{ etcd_release }}/etcd-v{{ etcd_release }}-linux-amd64.tar.gz
    dest: "{{ core_home }}"

# fix this
- name: Install Binary
  unarchive:
    src: "{{ core_home }}/etcd-v{{ etcd_release }}-linux-amd64.tar.gz"
    dest: /opt/bin/
    mode: 0655
    remote_src: yes

- name: Make etcd directories
  file:
    path: "{{ item }}"
    state: directory
  with_items: 
    - /etc/etcd
    - /var/lib/etcd 

- name: Copy keys into etcd 
  copy: 
    src: "{{ pki_dir }}/{{ item }}"
    dest: /etc/etcd
    remote_src: yes 
  with_items:
    - kubernetes-api.pem
    - kubernetes-api-key.pem

- name: Apply etcd template
  template:
    src: etcd.service.j2
    dest: /etc/systemd/system/etcd.service

