---
- name: Install CFSSL
  get_url:
    url: https://pkg.cfssl.org/R1.2/cfssl_linux-amd64
    dest: /opt/bin/cfssl
    mode: 0655
 
- name: Install CFSSL JSON
  get_url: 
    url: https://pkg.cfssl.org/R1.2/cfssljson_linux-amd64
    dest: /opt/bin/cfssljson
    mode: 0655

- name: Kube PKI dir
  file:
    path: "{{ pki_dir }}"
    state: directory
    owner: core
    group: core 

# CSR creation 
- name: Render CSRs
  template:
    src: csr.json.j2
    dest: "{{ pki_dir }}/{{ item.split('_')[0] }}-csr.json"
  vars:
    common_name: "{{ item.split('_')[1] }}"
  with_items:
   - ca_kubernetes
   - admin_system:masters
   - kube-controller-manager_system:kube-controller-manager
   - kube-proxy_system:kube-proxy
   - kube-scheduler_system:kube-scheduler
   - service-account_service-account
   - kubernetes-api_kube-api
   - node1_system:node:node1
   - node2_system:node:node2
   - node3_system:node:node3

# Certificate Authority creation  
- name: Create CA 
  shell: |
   cfssl gencert -initca ca-csr.json | cfssljson -bare ca
  args:
    chdir: "{{ pki_dir }}"
    creates: ca-key.pem

- name: CA Configuration template
  template: 
    src: ca-config.json.j2
    dest: "{{ pki_dir }}/ca-config.json"

# Certificate Signing
- name: Sign server cetificates 
  shell: |
    cfssl gencert \
    -ca=ca.pem \
    -ca-key=ca-key.pem \
    -config=ca-config.json \
    -profile=kubernetes {{ item }}-csr.json | cfssljson -bare {{ item }}
  with_items:
    - admin
    - kube-controller-manager
    - kube-scheduler
    - kube-proxy
    - service-account
  args: 
    chdir: "{{ pki_dir }}"
    creates: "{{ item }}-key.pem"

- name: Sign kubelet and kube-api cetificates 
  shell: |
    cfssl gencert \
    -ca=ca.pem \
    -ca-key=ca-key.pem \
    -config=ca-config.json \
    -hostname={{ item.split("_")[0] }},{{ item.split("_")[1] }},{{ item.split("_")[2] }} \
    -profile=kubernetes {{ item.split("_")[0] }}-csr.json | cfssljson -bare {{ item.split("_")[0] }}
  with_items:
    - node1_172.17.8.101_10.0.2.15
    - node2_172.17.8.102_10.0.2.15
    - node3_172.17.8.103_10.0.2.15
    - kubernetes-api_172.17.8.101_172.17.8.102,172.17.8.103,127.0.0.1,kuberentes.default
  args: 
    chdir: "{{ pki_dir }}"
    creates: "{{ item.split('_')[0] }}-key.pem"


